PROGRAM = child
FILES = child.cpp point_utils.cpp

all: build
build: clean

run:
	./$(PROGRAM).o

zip:
	rm -f $(PROGRAM).zip
	zip $(PROGRAM).zip *.cpp *.h makefile

build:
	g++ $(FILES) -o $(PROGRAM).o
    
clean:
	rm -f *.zip
	rm -f *.o
